version: '2'
services:
  emithraminsurance-app:
    image: emithraminsurance
    environment:
      - _JAVA_OPTIONS=-Xmx256m -Xms128m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8082:8082
